//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krea.opts {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.native-software.com/nsservlet/service.php", ConfigurationName="opts.NativeSecurityPort")]
    internal interface NativeSecurityPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.native-software.com/nsservlet/service.php#nsin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string nsin([System.ServiceModel.MessageParameterAttribute(Name="nsin")] string nsin1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface NativeSecurityPortChannel : Krea.opts.NativeSecurityPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class NativeSecurityPortClient : System.ServiceModel.ClientBase<Krea.opts.NativeSecurityPort>, Krea.opts.NativeSecurityPort {
        
        public NativeSecurityPortClient() {
        }
        
        public NativeSecurityPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NativeSecurityPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NativeSecurityPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NativeSecurityPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string nsin(string nsin1) {
            return base.Channel.nsin(nsin1);
        }
    }
}
